FROM golang:1.17 as builder
WORKDIR /build
COPY ./go.mod ./
COPY ./go.sum ./
RUN go mod download
COPY ./ ./
RUN CGO_ENABLED=0 go build -o ./bin/main ./src

FROM alpine:3.7
WORKDIR /app
COPY --from=builder /build/bin/main ./main
ENTRYPOINT ["./main"]
